app/models.py
#pylint: disable=no-member
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

order_details = db.Table(
    "order_details",
    db.Model.metadata,
    db.Column("order_id",db.Integer, db.ForeignKey("orders.id"), primary_key=True),
    db.Column("menu_item_id",db.Integer, db.ForeignKey("menu_items.id"), primary_key=True),
)


class Employee(db.Model, UserMixin):
    __tablename__ = "employees"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, nullable=False, unique=True)
    hashed_password = db.Column(db.String(100), nullable=False)

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    orders = db.relationship("Order")
    # details = db.relationship("OrderDetail")

class Menu(db.Model):
    __tablename__ = "menus"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)


class MenuItemType(db.Model):
    __tablename__ = "menu_item_types"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)


class MenuItem(db.Model):
    __tablename__ = "menu_items"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    menu_id = db.Column(db.Integer, db.ForeignKey("menus.id"), nullable=False)
    menu_type_id = db.Column(db.Integer, db.ForeignKey("menu_item_types.id"), nullable=False)
    
    type = db.relationship("MenuItemType")
    menu = db.relationship("Menu")

    orders = db.relationship("Order", secondary=order_details)


class Table(db.Model):
    __tablename__ = "tables"

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False, unique=True)
    capacity = db.Column(db.Integer, nullable=False)

    orders = db.relationship("Order")
    
class Order(db.Model):
    __tablename__ = "orders"

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employees.id"), nullable=False)
    table_id = db.Column(db.Integer, db.ForeignKey("tables.id"), nullable=False)
    finished = db.Column(db.Boolean, nullable=False)

    employee = db.relationship("Employee")
    table = db.relationship("Table")
    details = db.relationship("MenuItem", secondary=order_details, back_populates="orders")

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    StringField,
    PasswordField,
    SubmitField,
    BooleanField
)
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    employee_number = StringField('Employee Number', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')
    
class OrderForm(FlaskForm):
    french_fries = BooleanField('French Fries')
    dr_pepper = BooleanField('Dr. Pepper')
    jambalaya = BooleanField('Jambalaya')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from .config import Configuration
from .routes import orders, session
from .models import db, Employee

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)

login = LoginManager(app)
login.login_view = "session.login"


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required
from app.models import db, Table, MenuItem, Order
from sqlalchemy.orm import joinedload
from app.forms import OrderForm

bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/")
@login_required
def index():
    tables = list(Table.query.options(joinedload(Table.orders)).all())
    menu_items = list(MenuItem.query.options(joinedload(MenuItem.type)).all())
    form = OrderForm()
    return render_template("orders.html", tables=tables, menu=menu_items, form=form)

@bp.route("/table/<int:id>", methods=['POST', 'DELETE'])
@login_required
def table(id):
    form = OrderForm()
    if form.validate_on_submit():
        french_fries = form.french_fries.data
        dr_pepper = form.dr_pepper.data
        jambalaya = form.jambalaya.data
        order = Order.query.filter(Order.table_id==id).all()
        if order:
            pass
        else:
            order = Order() 
    return render_template("orders.html")

app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from app.forms import LoginForm
from app.models import Employee

bp = Blueprint("session", __name__, url_prefix="/session")

@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == empl_number).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)


@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

app/templates/base.html
<html>

    <head>
        {% if title %}
        <title>{{ title }} - Order Up!</title>
        {% else %}
        <title>Welcome to Order Up!</title>
        {% endif %}
    </head>

    <body>
        {% block content %}{% endblock %}

        {% if not current_user.is_anonymous %}
        <form method="POST" action="{{ url_for('session.logout') }}">
            <button>Logout</button>
        </form>
        {% endif %}
    </body>

</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}

    <h1>Order up!</h1>
    <form id="menu-items" method="POST" action="/">    
        {{ form.csrf_token }}
        <ul>
            <li>{{ form.french_fries.label }} {{ form.french_fries }}</li>
            <li>{{ form.dr_pepper.label }} {{ form.dr_pepper }}</li>
            <li>{{ form.jambalaya.label }} {{ form.jambalaya }}</li>
        </ul>

        <ul>
            {% for table in tables  %}
            <li> Table {{ table.number }}, capacity: {{ table.capacity }}, ${{ table.orders[0].details[0].price if table.orders[0] }} </li>
            {% if table.orders[0] and not table.orders[0].finished %}
            <button>CLOSE TABLE</button>
            {% endif %}

            <button form="menu-items" formaction="/table/{{ table.id }}">ADD TO ORDER</button>


            {% endfor %}
        </ul>
    </form>

{% endblock %}